name: Maven Compile, Test and Package Server

on:
  push:
    branches: 
      - "main" 
  pull_request:
    branches: 
      - "main" 

jobs:
  maven-compile-test-package:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
      
    - name: Change directory
      run: cd restful_api_demo

    - name: Run Maven clean
      run: mvn clean

    - name: Run Maven compile
      run: mvn compile

    - name: Run Maven test
      run: mvn test -DskipTests=false

    - name: Run Maven package
      run: mvn package -DskipTests=true
